service: cms-posts

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: posts.grida.cc
    certificateName: "*.grida.cc"
    basePath: ""
    createRoute53Record: true
    stage: production
  serverless-offline:
    httpPort: 4015
    noPrependStageInUrl: true
  optimize:
    external: ["@prisma/client", ".prisma/client"]

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
    # https://stackoverflow.com/questions/61003311/serverless-i-image-upload-to-s3-broken-after-deploy-local-worked-only/61003498#61003498
    binaryMediaTypes:
      - "*/*"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::cms-posts/*"

resource:
  s3bucket:
    Type: S3::Bucket
    Properties:
      BucketName: cms-posts

functions:
  main:
    handler: index.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors:
            origin: "*"

package:
  individually: true
  # only include the Prisma binary required on AWS Lambda while packaging
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"
